### ISSUE TITLE
when the mqtt-broker goes down (e.g. for maintenance), the setup crashes and comes never back online 

### ISSUE THREAD

**Issue by Baxxy13** [nygma2004/sdm1202mqtt#2]
When running normally and the mqtt-broker goes down the system tries to reconnect once and then crashes,

After that the system comes never back online, even if the mqtt-broker is back up.

It seems that after the crash the system can't connect to the configured wifi anymore.

It could be related to #1 because if i test the situation without sdm120m connected, the setup retries to connect every 5s and connects successfully if the mqtt-broker is back on.

I append a logfile from both situations.

Maybe cou could have a look.

[mqtt-broker_down_sdm120m_connected.txt](https://github.com/nygma2004/sdm1202mqtt/files/10851946/mqtt-broker_down_sdm120m_connected.txt)
[mqtt-broker_down_sdm120m_disconnected.txt](https://github.com/nygma2004/sdm1202mqtt/files/10851949/mqtt-broker_down_sdm120m_disconnected.txt)

Greetings from Berlin,
Baxxy

**Comment by nygma2004** [comment]
Hi Baxxy,

This is though, because I don't have any idea why this is happening. And also the crash cycle mentioned in Issue #1. In my setup the ESP restarts every day multiple times as the power goes away and comes back and I experience no issues at all. Do you have the possibility to swap hardware components? The Wemos D1 mini and the RS485 module?

**Comment by Baxxy13** [comment]
The solution was to additionally connect GND from the setup to port 8 [G] of the sdm120m.
Now it doesn't crash anymore when the mqtt-broker goes down and reconnects successfully when the broker comes up again.

Case closed. 😉
